---
language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - nightly
matrix:
  allow_failures:
    - php: 5.6

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - if [ $(phpenv version-name) = "5.6" ]; then composer require paragonie/random_compat:2.0.17; fi
  - if [ $(phpenv version-name) = "5.6" ]; then composer require phpunit/phpunit:4.8.36; fi
  - composer install

script: composer test
