---
language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - if [ $(phpenv version-name) = "5.6" ]; then composer remove --dev phpunit/phpunit; fi
  - if [ $(phpenv version-name) = "5.6" ]; then composer require --dev phpunit/phpunit:4.8.36; fi
  - if [ $(phpenv version-name) = "5.6" ]; then composer require --dev paragonie/random_compat:2.0.17; fi
  - composer install

script: composer test
