---
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer update
  - if [ $(phpenv version-name) = "5.4" ] || [ $(phpenv version-name) = "5.5" ] || [ $(phpenv version-name) = "5.6" ]; then composer require --dev paragonie/random_compat:2.0.17; fi

script: composer test

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.3
      before_script:
        - composer global require friendsofphp/php-cs-fixer
      script:
        - php-cs-fixer fix --config=.php_cs.dist --dry-run -v --show-progress=dots --diff-format=udiff src tests
