---
language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer update
  - if [ $(phpenv version-name) = "5.6" ]; then composer require --dev paragonie/random_compat:2.0.17; fi

script: composer test
